name: Build all projects

on: [pull_request]

jobs: 
  API:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
        source-url: https://nuget.pkg.github.com/mplaisier/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.TOKEN}}
    - name: Restore dependencies
      run: |
        cd ThePage
        dotnet restore
    - name: Build
      run: |
        cd ThePage
        dotnet build src/ThePage.Api/ThePage.Api.csproj --no-restore -c Unit-Test

  Core:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
        source-url: https://nuget.pkg.github.com/mplaisier/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.TOKEN}}
    - name: Build
      run: |
        cd ThePage
        nuget restore
        msbuild src/ThePage.Core/ThePage.Core.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
        source-url: https://nuget.pkg.github.com/mplaisier/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.TOKEN}}
    - name: Build
      run: |
        cd ThePage
        nuget restore
        msbuild src/ThePage.Droid/ThePage.Droid.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
        source-url: https://nuget.pkg.github.com/mplaisier/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.TOKEN}}
    - name: Build
      run: |
        cd ThePage
        nuget restore
        msbuild src/ThePage.iOS/ThePage.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
        
  UnitTests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
        source-url: https://nuget.pkg.github.com/mplaisier/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.TOKEN}}
    - name: Build
      run: |
        cd ThePage
        nuget restore
        msbuild src/ThePage.UnitTests/ThePage.UnitTests.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug        
