name: CI on Push and Pull Request

on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'
       
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: |
        cd ThePage
        dotnet restore
    - name: Build
      run: |
        cd ThePage
        dotnet build --configuration $config --no-restore
    - name: Test
      run: |
        cd ThePage
        dotnet test --no-restore --no-build --configuration $config 
  
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd ThePage
        nuget restore
        msbuild src/ThePage.Droid/ThePage.Droid.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd ThePage
        nuget restore
        msbuild src/ThePage.iOS/ThePage.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
        
  UnitTests:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v1
      - name: Unit tests
        run: |
          cd ThePage
          nuget restore
          msbuild
          msbuild src/ThePage.UnitTests/ThePage.UnitTests.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug        
